db.productos.insertMany([
    {_id: 1,producto: "Chorizo rosario", cantidad:{num:10, unid:"kg"}, preciovp: 6.62, proveedor: "Angel Lopez", precio: 5.99, categoria:"Chacina"},
    {_id: 2,producto: "Morcilla de higado", cantidad:{num:25, unid:"kg"}, preciovp: 5.59, proveedor: "Hispasur", precio: 4.85, categoria:"Carne"},
    {_id: 3, producto: "Salchichon vela extra", cantidad:{num:30, unid:"kg"}, preciovp: 8.3, proveedor: "Adan", precio: 6.12, categoria:"Chacina"},
    {_id: 4, producto: "Cabeza de lomo mechada", cantidad:{num:12, unid:"kg"}, preciovp: 12.04, proveedor: "Angel Lopez", precio: 10.05, categoria:"Chacina"},
    {_id: 5, producto: "Butifarra andaluza", cantidad:{num:17, unid:"kg"}, preciovp: 6.64, proveedor: "Angel Lopez", precio: 6, categoria:"Chacina"},
    {_id: 6, producto: "Chicharron serrano", cantidad:{num:6.5, unid:"kg"}, preciovp: 12.11, proveedor: "Adan", precio: 11.05, categoria:"Chacina"},
    {_id: 7, producto: "Chicharron tradicional", cantidad:{num:14, unid:"kg"}, preciovp: 14.46, proveedor: "Angel Lopez", precio: 12.78, categoria:"Chacina"},
    {_id: 8, producto: "Hamburguesas de pollo", cantidad:{num:18, unid:"bandejas"}, preciovp: 4.21, proveedor: "Hispasur", precio: 3.89, categoria:"Carne"},
    {_id: 9, producto: "Salchichas de pollo", cantidad:{num:21, unid:"bandejas"}, preciovp: 3.53, proveedor: "Recio", precio: 2.18, categoria:"Carne", oferta: ["11x9","6x5","20x15"]},
    {_id: 10, producto: "Chistorras de granel", cantidad:{num:14, unid:"bandejas"}, preciovp: 7.45, proveedor: "Angel Lopez", precio: 6.75, categoria:"Chacina"},
    {_id: 11, producto: "Zurrapa lomo colorada", cantidad:{num:37, unid:"bandejas"}, preciovp: 1.69, proveedor: "Recio", precio: 0.45, categoria:"Chacina"},
    {_id: 12, producto: "Loncha chorizo", cantidad:{num:9, unid:"bandejas"}, preciovp: 0.78, proveedor: "Hispasur", precio: 0.38, categoria:"Carne"},
    {_id: 13, producto: "Patatas fritas", cantidad:{num:32, unid:"paquetes"}, preciovp: 1.35, proveedor: "Hispasur", precio: 0.99, categoria:"Aperitivo"},
    {_id: 14, producto: "Langostinos buque", cantidad:{num:24, unid:"cubos"}, preciovp: 7.76, proveedor: "Recio", precio: 5.35, categoria:"Molusco"},
    {_id: 15, producto: "Tarta Tiramisu mini", cantidad:{num:9, unid:"unidades"}, preciovp: 25.92, proveedor: "Marclem", precio: 21.87, categoria:"Tarta", oferta:["6x5"]},
    {_id: 16, producto: "Caracoles", cantidad:{num:42, unid:"cubos"}, preciovp: 6.49, proveedor: "Recio", precio: 5.65, categoria:"Molusco"},
    {_id: 17, producto: "Cabrillas", cantidad:{num:32, unid:"cubos"}, preciovp: 8.49, proveedor: "Hispasur", precio: 7.19, categoria:"Molusco"},
    {_id: 18, producto: "Cheetos Pelotazos", cantidad:{num:12, unid:"paquetes"}, preciovp: 0.95, proveedor: "Frito-Lay", precio: 0.9, categoria:"Aperitivo"},
    {_id: 19, producto: "Cheetos Rizos", cantidad:{num:28, unid:"paquetes"}, preciovp: 0.95, proveedor: "Frito-Lay", precio: 0.9, categoria:"Aperitivo"},
    {_id: 20, producto: "Cheetos Fantasmas", cantidad:{num:16, unid:"paquetes"}, preciovp: 0.95, proveedor: "Frito-Lay", precio: 0.9, categoria:"Aperitivo"},
    {_id: 21, producto: "Cheetos Gusanitos", cantidad:{num:4, unid:"paquetes"}, preciovp: 0.95, proveedor: "Frito-Lay", precio: 0.9, categoria:"Aperitivo"},
    {_id: 22, producto: "Tarta Vichyssoise", cantidad:{num:2, unid:"unidades"}, preciovp: 18.89, proveedor: "Marclem", precio: 14.25, categoria:"Tarta"},
    {_id: 23, producto: "Tarta tres paladares", cantidad:{num:3, unid:"unidades"}, preciovp: 29.99, proveedor: "Marclem", precio: 22.05, categoria:"Tarta"},
    {_id: 24, producto: "Pechuga de pavo", cantidad:{num:17, unid:"kg"}, preciovp: 8.93, proveedor: "Angel Lopez", precio: 7.99, categoria:"Carne"},
    {_id: 25, producto: "Manzanas Rallsgenet", cantidad:{num:12, unid:"bolsas"}, preciovp: 5.42, proveedor: "Adan", precio: 3.99, categoria:"Fruta", oferta:["3x2","2x1"]},
    {_id: 26, producto: "Platanos canarios", cantidad:{num:21, unid:"bolsas"}, preciovp: 6.99, proveedor: "Marclem", precio: 5.87, categoria:"Fruta", oferta:["3x2","6x5","2x1"]},
    {_id: 27, producto: "Gambas antorcha", cantidad:{num:25, unid:"cubos"}, preciovp: 25.92, proveedor: "Recio", precio: 22.89, categoria:"Molusco", oferta:["6x5","12x10"]},
]);

db.pedidos.insertMany([
    {_id: 1, producto: "Chorizo rosario", cantidad: 3, precio: 19.96, localidad: "Sevilla", fechaPedido: new Date("2017,05,01"), fechaEntrega: new Date("2017,05,07"), retraso: true},
    {_id: 2, producto: "Chicharron serrano", cantidad: 4.5, precio: 54.95, localidad: "Moron", fechaPedido: new Date("2017,05,03"), fechaEntrega: new Date("2017,05,04"), retraso: false},
    {_id: 3, producto: "Morchilla de higado", cantidad: 2, precio: 11.18, localidad: "Sevilla", fechaPedido: new Date("2017,05,06"), fechaEntrega: new Date("2017,05,08"), retraso: true},
    {_id: 4, producto: "Hamburguesa de pollo", cantidad: 7, precio: 29.47, localidad: "Arahal", fechaPedido: new Date("2017,05,04"), fechaEntrega: new Date("2017,05,09"), retraso: true},
    {_id: 5, producto: "Caracoles", cantidad: 24, precio: 155.76, localidad: "Sevilla", fechaPedido: new Date("2017,05,09"), fechaEntrega: new Date("2017,05,09"), retraso: false},
    {_id: 6, producto: "Cabeza de lomo", cantidad: 10, precio: 120.40, localidad: "Sevilla", fechaPedido: new Date("2017,06,11"), fechaEntrega: new Date("2017,06,16"), retraso: false},
    {_id: 7, producto: "Cabrillas", cantidad: 19, precio: 161.31, localidad: "Arahal", fechaPedido: new Date("2017,06,24"), fechaEntrega: new Date("2017,06,26"), retraso: true},
    {_id: 8, producto: "Cabrillas", cantidad: 9, precio: 76.41, localidad: "Arahal", fechaPedido: new Date("2017,06,25"), fechaEntrega: new Date("2017,06,26"), retraso: true},
    {_id: 9, producto: "Cabrillas", cantidad: 3, precio: 25.47, localidad: "Arahal", fechaPedido: new Date("2017,07,01"), fechaEntrega: new Date("2017,07,11"), retraso: true},
    {_id: 10, producto: "Loncha chorizo", cantidad: 11, precio: 9.06, localidad: "Arahal", fechaPedido: new Date("2017,06,16"), fechaEntrega: new Date("2017,06,17"), retraso: false},    
    {_id: 11, producto: "Salchichas de pollo", cantidad: 12, precio: 42.36, localidad: "Sevilla", fechaPedido: new Date("2017,06,17"), fechaEntrega: new Date("2017,06,19"), retraso: false},
    {_id: 12, producto: "Cheetos gusanitos", cantidad: 4, precio: 4.20, localidad: "Sevilla", fechaPedido: new Date("2017,06,17"), fechaEntrega: new Date("2017,06,20"), retraso: false},
    {_id: 13, producto: "Cabrillas", cantidad: 21, precio: 178.29, localidad: "Moron", fechaPedido: new Date("2018,06,16"), fechaEntrega: new Date("2018,06,17"), retraso: false},
    {_id: 14, producto: "Tarta tres paladares", cantidad: 1, precio: 29.99, localidad: "Sevilla", fechaPedido: new Date("2018,07,19"), fechaEntrega: new Date("2018,07,23"), retraso: true},
    {_id: 15, producto: "Caracoles", cantidad: 11, precio: 71.39, localidad: "Moron", fechaPedido: new Date("2018,07,19"), fechaEntrega: new Date("2018,07,23"), retraso: true},
    {_id: 16, producto: "Salchichas de pollo", cantidad: 16, precio: 56.48, localidad: "Sevilla", fechaPedido: new Date("2018,07,20"), fechaEntrega: new Date("2018,07,24"), retraso: true},
    {_id: 17, producto: "Chorizo rosario", cantidad: 3, precio: 19.96, localidad: "Arahal", fechaPedido: new Date("2018,07,20"), fechaEntrega: new Date("2018,07,24"), retraso: true},
    {_id: 18, producto: "Langostinos buque", cantidad: 8, precio: 62.08, localidad: "Sevilla", fechaPedido: new Date("2018,07,20"), fechaEntrega: new Date("2018,07,25"), retraso: false},
    {_id: 19, producto: "Morchilla de higado", cantidad: 6, precio: 33.54, localidad: "Sevilla", fechaPedido: new Date("2018,07,21"), fechaEntrega: new Date("2018,07,26"), retraso: false},
    {_id: 20, producto: "Chistorras grane", cantidad: 21, precio: 156.45, localidad: "Sevilla",  fechaPedido: new Date("2019,08,23"), fechaEntrega: new Date("2019,08,29"), retraso: true},
    {_id: 21, producto: "Chicharron tradicional", cantidad: 8, precio: 115.84, localidad: "Arahal", fechaPedido: new Date("2019,08,23"), fechaEntrega: new Date("2019,08,29"), retraso: true},
    {_id: 22, producto: "Cheetos pellotazos", cantidad: 5, precio: 5.25, localidad: "Sevilla", fechaPedido: new Date("2019,08,25"), fechaEntrega: new Date("2019,08,29"), retraso: false},
    {_id: 23, producto: "Cheetos fantasmas", cantidad: 4, precio: 3.80, localidad: "Moron", fechaPedido: new Date("2019,08,25"), fechaEntrega: new Date("2019,08,30"), retraso: false},
    {_id: 24, producto: "Pechuga de pavo", cantidad: 15, precio: 133.95, localidad: "Sevilla", fechaPedido: new Date("2019,08,27"), fechaEntrega: new Date("2019,09,01"), retraso: false},
    {_id: 25, producto: "Caracoles", cantidad: 7, precio: 45.18, localidad: "Moron", fechaPedido: new Date("2019,07,19"), fechaEntrega: new Date("2019,07,21"), retraso: true},
    {_id: 26, producto: "Caracoles", cantidad: 11, precio: 71.39, localidad: "Moron", fechaPedido: new Date("2019,07,21"), fechaEntrega: new Date("2019,07,22"), retraso: false},
    {_id: 27, producto: "Caracoles", cantidad: 16, precio: 103.27, localidad: "Moron", fechaPedido: new Date("2019,07,20"), fechaEntrega: new Date("2019,07,21"), retraso: true},
    {_id: 28, producto: "Morchilla de higado", cantidad: 81, precio: 452.79, localidad: "Sevilla", fechaPedido: new Date("2020,01,2"), fechaEntrega: new Date("2020,01,06"), retraso: true},
])
